### ISSUE TITLE
Benchmark sqlite vs fst

### ISSUE THREAD

**Issue by izahn** [NSAPH/software_systems_documentation#8]
It would be good to do some comparisons of the time required for various data extractions via sqlite versus sharded `.fst` files. A sqlite database for this purpose lives at `/nfs/nsaph_ci3/ci3_health_data/medicare/mortality/1999_2016/wu/output_data` and the corresponding `.fst` directory is `/nfs/nsaph_ci3/ci3_health_data/medicare/mortality/1999_2016/wu/cache_data/merged_by_year`. We should compare different types of extraction, e.g., a small number of columns across all years, a large number of columns across a small number of years. We should also compare extracting times for things we haven't sharded on, e.g., extraction time for New England states 2008 -- 2010 (this will require on-the-fly or post-extraction filtering of the `.fst` data)

Lets do this in the https://github.com/NSAPH/software_systems_documentation/tree/shard_benchmarks branch and do a pull request when its ready.

**Comment by mbsabath** [comment]
Got the benchmarking infrastructure created on friday. Running the benchmarks now. Will push the results once they complete

**Comment by mbsabath** [comment]
Results in https://github.com/NSAPH/software_systems_documentation/pull/9, closing this now
